train_SVM:
	python train.py SVM_Classifier
train_K_Neighbor:
	python train.py K_Neighbor
train_Gaussian:
	python train.py Gaussian
train_Ada:
	python train.py Ada
train_RandomForest:
	python train.py RandomForest
train_RBF_SVM:
	python train.py RBF_SVM

SVM:
	python detector.py SVM_Classifier
K_Neighbor:
	python detector.py K_Neighbor
Gaussian:
	python detector.py Gaussian
Ada:
	python detector.py Ada
RandomForest:
	python detector.py RandomForest
RBF_SVM:
	python detector.py RBF_SVM

train_all:
	python train.py SVM_Classifier
	python train.py K_Neighbor
	python train.py Gaussian
	python train.py Ada
	python train.py RandomForest
	python train.py RBF_SVM

run_all:
	python detector.py SVM_Classifier
	python detector.py Ada
	python detector.py RandomForest
	python detector.py Gaussian
	python detector.py K_Neighbor
	python detector.py RBF_SVM

all:
	python train.py SVM_Classifier
	python train.py K_Neighbor
	python train.py Gaussian
	python train.py Ada
	python train.py RandomForest
	python train.py RBF_SVM
	python detector.py SVM_Classifier
	python detector.py Ada
	python detector.py RandomForest
	python detector.py Gaussian
	python detector.py K_Neighbor
	python detector.py RBF_SVM
